version: '3.8'

services:
  diagrams-workflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diagrams-workflow-api
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TEMP_DIR=/tmp/diagrams-workflow
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    volumes:
      # Mount temp directory for diagram files
      - diagram_temp:/tmp/diagrams-workflow
      # Mount source code for development (comment out for production)
      - ./src:/app/src:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Development override service
  diagrams-workflow-dev:
    extends: diagrams-workflow
    environment:
      - DEBUG_MODE=true
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      - ./src:/app/src
    command: ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev

volumes:
  diagram_temp:
    driver: local